# -*- mode: makefile-gmake; mode: flyspell-prog; -*-

COMPONENT=TemperatureAppC
PFLAGS+=-I%T/chips/max6951
PFLAGS+=-I%T/chips/ds1624
include $(TINYOS_ROOT_DIR)/Makefile.include

# vim: set noet ts=8 sw=8:
