/**
 * Copyright (c) 2009 DEXMA SENSORS SL
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *   documentation and/or other materials provided with the
 *   distribution.
 * - Neither the name of the DEXMA SENSORS SL nor the names of
 *   its contributors may be used to endorse or promote products derived
 *   from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
 * DEXMA SENSORS SL OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE
 */

/* "Copyright (c) 2000-2003 The Regents of the University of California.  
 * All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement
 * is hereby granted, provided that the above copyright notice, the following
 * two paragraphs and the author appear in all copies of this software.
 * 
 * IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE UNIVERSITY
 * OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS."
 */

/*
 * @author Cory Sharp <cssharp@eecs.berkeley.edu>
 * @author Xavier Orduna <xorduna@dexmatech.com>
*/

#ifndef _H_msp430regtypes_h
#define _H_msp430regtypes_h

/*
  To generate the primary contents of this file seen below, in
  mspgcc/msp430/include/, execute the following command:

    find . | xargs perl -ne '
      BEGIN { %t = qw(b uint8_t w uint16_t); }
      if( /\bsfr([bw])\s*\(\s*(\w+)/ && length($2) > 1 ) {
        $r{$2} = $t{$1};
        print "#define TYPE_$2 $t{$1}\n" if /\bsfr([bw])\s*\(\s*(\w+)/;
      } elsif( /^#define\s+(\w+)\s+(\w+)\s+$/ ) {
        print "#define TYPE_$1 $r{$2}\n" if $r{$2};
      }
    ' | sort -u
*/

#define TYPE_0x23C0 uint8_t
#define TYPE_0x23C7 uint8_t
#define TYPE_ACTL uint16_t
#define TYPE_ADAT uint16_t
#define TYPE_ADC10AE uint8_t
#define TYPE_ADC10AE0 uint8_t
#define TYPE_ADC10AE1 uint8_t
#define TYPE_ADC10CTL0 uint16_t
#define TYPE_ADC10CTL0_H uint8_t
#define TYPE_ADC10CTL0_L uint8_t
#define TYPE_ADC10CTL1 uint16_t
#define TYPE_ADC10CTL1_H uint8_t
#define TYPE_ADC10CTL1_L uint8_t
#define TYPE_ADC10CTL2 uint16_t
#define TYPE_ADC10CTL2_H uint8_t
#define TYPE_ADC10CTL2_L uint8_t
#define TYPE_ADC10DTC0 uint8_t
#define TYPE_ADC10DTC1 uint8_t
#define TYPE_ADC10HI uint16_t
#define TYPE_ADC10HI_H uint8_t
#define TYPE_ADC10HI_L uint8_t
#define TYPE_ADC10IE uint16_t
#define TYPE_ADC10IE_H uint8_t
#define TYPE_ADC10IE_L uint8_t
#define TYPE_ADC10IFG uint16_t
#define TYPE_ADC10IFG_H uint8_t
#define TYPE_ADC10IFG_L uint8_t
#define TYPE_ADC10IV uint16_t
#define TYPE_ADC10IV_H uint8_t
#define TYPE_ADC10IV_L uint8_t
#define TYPE_ADC10LO uint16_t
#define TYPE_ADC10LO_H uint8_t
#define TYPE_ADC10LO_L uint8_t
#define TYPE_ADC10MCTL0 uint16_t
#define TYPE_ADC10MCTL0_H uint8_t
#define TYPE_ADC10MCTL0_L uint8_t
#define TYPE_ADC10MEM uint16_t
#define TYPE_ADC10MEM0 uint16_t
#define TYPE_ADC10MEM0_H uint8_t
#define TYPE_ADC10MEM0_L uint8_t
#define TYPE_ADC10SA uint16_t
#define TYPE_ADC12CTL0 uint16_t
#define TYPE_ADC12CTL0_H uint8_t
#define TYPE_ADC12CTL0_L uint8_t
#define TYPE_ADC12CTL1 uint16_t
#define TYPE_ADC12CTL1_H uint8_t
#define TYPE_ADC12CTL1_L uint8_t
#define TYPE_ADC12CTL2 uint16_t
#define TYPE_ADC12CTL2_H uint8_t
#define TYPE_ADC12CTL2_L uint8_t
#define TYPE_ADC12IE uint16_t
#define TYPE_ADC12IE_H uint8_t
#define TYPE_ADC12IE_L uint8_t
#define TYPE_ADC12IFG uint16_t
#define TYPE_ADC12IFG_H uint8_t
#define TYPE_ADC12IFG_L uint8_t
#define TYPE_ADC12IV uint16_t
#define TYPE_ADC12IV_H uint8_t
#define TYPE_ADC12IV_L uint8_t
#define TYPE_ADC12MCTL0 uint8_t
#define TYPE_ADC12MCTL1 uint8_t
#define TYPE_ADC12MCTL10 uint8_t
#define TYPE_ADC12MCTL11 uint8_t
#define TYPE_ADC12MCTL12 uint8_t
#define TYPE_ADC12MCTL13 uint8_t
#define TYPE_ADC12MCTL14 uint8_t
#define TYPE_ADC12MCTL15 uint8_t
#define TYPE_ADC12MCTL2 uint8_t
#define TYPE_ADC12MCTL3 uint8_t
#define TYPE_ADC12MCTL4 uint8_t
#define TYPE_ADC12MCTL5 uint8_t
#define TYPE_ADC12MCTL6 uint8_t
#define TYPE_ADC12MCTL7 uint8_t
#define TYPE_ADC12MCTL8 uint8_t
#define TYPE_ADC12MCTL9 uint8_t
#define TYPE_ADC12MEM0 uint16_t
#define TYPE_ADC12MEM0_H uint8_t
#define TYPE_ADC12MEM0_L uint8_t
#define TYPE_ADC12MEM1 uint16_t
#define TYPE_ADC12MEM10 uint16_t
#define TYPE_ADC12MEM10_H uint8_t
#define TYPE_ADC12MEM10_L uint8_t
#define TYPE_ADC12MEM11 uint16_t
#define TYPE_ADC12MEM11_H uint8_t
#define TYPE_ADC12MEM11_L uint8_t
#define TYPE_ADC12MEM12 uint16_t
#define TYPE_ADC12MEM12_H uint8_t
#define TYPE_ADC12MEM12_L uint8_t
#define TYPE_ADC12MEM13 uint16_t
#define TYPE_ADC12MEM13_H uint8_t
#define TYPE_ADC12MEM13_L uint8_t
#define TYPE_ADC12MEM14 uint16_t
#define TYPE_ADC12MEM14_H uint8_t
#define TYPE_ADC12MEM14_L uint8_t
#define TYPE_ADC12MEM15 uint16_t
#define TYPE_ADC12MEM15_H uint8_t
#define TYPE_ADC12MEM15_L uint8_t
#define TYPE_ADC12MEM1_H uint8_t
#define TYPE_ADC12MEM1_L uint8_t
#define TYPE_ADC12MEM2 uint16_t
#define TYPE_ADC12MEM2_H uint8_t
#define TYPE_ADC12MEM2_L uint8_t
#define TYPE_ADC12MEM3 uint16_t
#define TYPE_ADC12MEM3_H uint8_t
#define TYPE_ADC12MEM3_L uint8_t
#define TYPE_ADC12MEM4 uint16_t
#define TYPE_ADC12MEM4_H uint8_t
#define TYPE_ADC12MEM4_L uint8_t
#define TYPE_ADC12MEM5 uint16_t
#define TYPE_ADC12MEM5_H uint8_t
#define TYPE_ADC12MEM5_L uint8_t
#define TYPE_ADC12MEM6 uint16_t
#define TYPE_ADC12MEM6_H uint8_t
#define TYPE_ADC12MEM6_L uint8_t
#define TYPE_ADC12MEM7 uint16_t
#define TYPE_ADC12MEM7_H uint8_t
#define TYPE_ADC12MEM7_L uint8_t
#define TYPE_ADC12MEM8 uint16_t
#define TYPE_ADC12MEM8_H uint8_t
#define TYPE_ADC12MEM8_L uint8_t
#define TYPE_ADC12MEM9 uint16_t
#define TYPE_ADC12MEM9_H uint8_t
#define TYPE_ADC12MEM9_L uint8_t
#define TYPE_AEN uint16_t
#define TYPE_AESACTL0 uint16_t
#define TYPE_AESACTL0_H uint8_t
#define TYPE_AESACTL0_L uint8_t
#define TYPE_AESADIN uint16_t
#define TYPE_AESADIN_H uint8_t
#define TYPE_AESADIN_L uint8_t
#define TYPE_AESADOUT uint16_t
#define TYPE_AESADOUT_H uint8_t
#define TYPE_AESADOUT_L uint8_t
#define TYPE_AESAKEY uint16_t
#define TYPE_AESAKEY_H uint8_t
#define TYPE_AESAKEY_L uint8_t
#define TYPE_AESASTAT uint16_t
#define TYPE_AESASTAT_H uint8_t
#define TYPE_AESASTAT_L uint8_t
#define TYPE_AIN uint16_t
#define TYPE_APCNF uint16_t
#define TYPE_APCNF_H uint8_t
#define TYPE_APCNF_L uint8_t
#define TYPE_APCTL uint16_t
#define TYPE_APCTL_H uint8_t
#define TYPE_APCTL_L uint8_t
#define TYPE_APFRACT uint16_t
#define TYPE_APFRACTB uint16_t
#define TYPE_APFRACTB_H uint8_t
#define TYPE_APFRACTB_L uint8_t
#define TYPE_APFRACT_H uint8_t
#define TYPE_APFRACT_L uint8_t
#define TYPE_APIE uint16_t
#define TYPE_APIE_H uint8_t
#define TYPE_APIE_L uint8_t
#define TYPE_APIFG uint16_t
#define TYPE_APIFG_H uint8_t
#define TYPE_APIFG_L uint8_t
#define TYPE_APINT uint16_t
#define TYPE_APINTB uint16_t
#define TYPE_APINTB_H uint8_t
#define TYPE_APINTB_L uint8_t
#define TYPE_APINT_H uint8_t
#define TYPE_APINT_L uint8_t
#define TYPE_APOMR uint16_t
#define TYPE_APOMR_H uint8_t
#define TYPE_APOMR_L uint8_t
#define TYPE_APTRIM uint16_t
#define TYPE_APTRIM_H uint8_t
#define TYPE_APTRIM_L uint8_t
#define TYPE_APVDIV uint16_t
#define TYPE_APVDIV_H uint8_t
#define TYPE_APVDIV_L uint8_t
#define TYPE_BAKCHCTL uint16_t
#define TYPE_BAKCHCTL_H uint8_t
#define TYPE_BAKCHCTL_L uint8_t
#define TYPE_BAKCTL uint16_t
#define TYPE_BAKCTL_H uint8_t
#define TYPE_BAKCTL_L uint8_t
#define TYPE_BAKMEM0 uint16_t
#define TYPE_BAKMEM0_H uint8_t
#define TYPE_BAKMEM0_L uint8_t
#define TYPE_BAKMEM1 uint16_t
#define TYPE_BAKMEM1_H uint8_t
#define TYPE_BAKMEM1_L uint8_t
#define TYPE_BAKMEM2 uint16_t
#define TYPE_BAKMEM2_H uint8_t
#define TYPE_BAKMEM2_L uint8_t
#define TYPE_BAKMEM3 uint16_t
#define TYPE_BAKMEM3_H uint8_t
#define TYPE_BAKMEM3_L uint8_t
#define TYPE_BCD2BIN uint16_t
#define TYPE_BCSCTL1 uint8_t
#define TYPE_BCSCTL2 uint8_t
#define TYPE_BCSCTL3 uint8_t
#define TYPE_BIN2BCD uint16_t
#define TYPE_BTCNT1 uint8_t
#define TYPE_BTCNT12 uint16_t
#define TYPE_BTCNT2 uint8_t
#define TYPE_BTCTL uint8_t
#define TYPE_CACTL1 uint8_t
#define TYPE_CACTL2 uint8_t
#define TYPE_CALBC1_12MHZ uint8_t
#define TYPE_CALBC1_16MHZ uint8_t
#define TYPE_CALBC1_1MHZ uint8_t
#define TYPE_CALBC1_8MHZ uint8_t
#define TYPE_CALDCO_12MHZ uint8_t
#define TYPE_CALDCO_16MHZ uint8_t
#define TYPE_CALDCO_1MHZ uint8_t
#define TYPE_CALDCO_8MHZ uint8_t
#define TYPE_CAPD uint8_t
#define TYPE_CBCTL uint8_t
#define TYPE_CBCTL0 uint16_t
#define TYPE_CBCTL0_H uint8_t
#define TYPE_CBCTL0_L uint8_t
#define TYPE_CBCTL1 uint16_t
#define TYPE_CBCTL1_H uint8_t
#define TYPE_CBCTL1_L uint8_t
#define TYPE_CBCTL2 uint16_t
#define TYPE_CBCTL2_H uint8_t
#define TYPE_CBCTL2_L uint8_t
#define TYPE_CBCTL3 uint16_t
#define TYPE_CBCTL3_H uint8_t
#define TYPE_CBCTL3_L uint8_t
#define TYPE_CBINT uint16_t
#define TYPE_CBINT_H uint8_t
#define TYPE_CBINT_L uint8_t
#define TYPE_CBIV uint16_t
#define TYPE_CCR0 uint16_t
#define TYPE_CCR1 uint16_t
#define TYPE_CCR2 uint16_t
#define TYPE_CCSCTL0 uint16_t
#define TYPE_CCSCTL0_H uint8_t
#define TYPE_CCSCTL0_L uint8_t
#define TYPE_CCSCTL1 uint16_t
#define TYPE_CCSCTL1_H uint8_t
#define TYPE_CCSCTL1_L uint8_t
#define TYPE_CCSCTL2 uint16_t
#define TYPE_CCSCTL2_H uint8_t
#define TYPE_CCSCTL2_L uint8_t
#define TYPE_CCSCTL4 uint16_t
#define TYPE_CCSCTL4_H uint8_t
#define TYPE_CCSCTL4_L uint8_t
#define TYPE_CCSCTL5 uint16_t
#define TYPE_CCSCTL5_H uint8_t
#define TYPE_CCSCTL5_L uint8_t
#define TYPE_CCSCTL6 uint16_t
#define TYPE_CCSCTL6_H uint8_t
#define TYPE_CCSCTL6_L uint8_t
#define TYPE_CCSCTL7 uint16_t
#define TYPE_CCSCTL7_H uint8_t
#define TYPE_CCSCTL7_L uint8_t
#define TYPE_CCSCTL8 uint16_t
#define TYPE_CCSCTL8_H uint8_t
#define TYPE_CCSCTL8_L uint8_t
#define TYPE_CCTL0 uint16_t
#define TYPE_CCTL1 uint16_t
#define TYPE_CCTL2 uint16_t
#define TYPE_CRCDI uint16_t
#define TYPE_CRCDIRB uint16_t
#define TYPE_CRCDIRB_H uint8_t
#define TYPE_CRCDIRB_L uint8_t
#define TYPE_CRCDI_H uint8_t
#define TYPE_CRCDI_L uint8_t
#define TYPE_CRCINIRES uint16_t
#define TYPE_CRCINIRES_H uint8_t
#define TYPE_CRCINIRES_L uint8_t
#define TYPE_CRCRESR uint16_t
#define TYPE_CRCRESR_H uint8_t
#define TYPE_CRCRESR_L uint8_t
#define TYPE_DAC12_0CALCTL uint16_t
#define TYPE_DAC12_0CALDAT uint16_t
#define TYPE_DAC12_0CTL uint16_t
#define TYPE_DAC12_0CTL0 uint16_t
#define TYPE_DAC12_0CTL1 uint16_t
#define TYPE_DAC12_0DAT uint16_t
#define TYPE_DAC12_1CALCTL uint16_t
#define TYPE_DAC12_1CALDAT uint16_t
#define TYPE_DAC12_1CTL uint16_t
#define TYPE_DAC12_1CTL0 uint16_t
#define TYPE_DAC12_1CTL1 uint16_t
#define TYPE_DAC12_1DAT uint16_t
#define TYPE_DAC12_IV uint16_t
#define TYPE_DCOCTL uint8_t
#define TYPE_DMA0CTL uint16_t
#define TYPE_DMA0CTL_H uint8_t
#define TYPE_DMA0CTL_L uint8_t
#define TYPE_DMA0DA uint16_t
#define TYPE_DMA0DAL uint16_t
#define TYPE_DMA0SA uint16_t
#define TYPE_DMA0SAL uint16_t
#define TYPE_DMA0SZ uint16_t
#define TYPE_DMA1CTL uint16_t
#define TYPE_DMA1CTL_H uint8_t
#define TYPE_DMA1CTL_L uint8_t
#define TYPE_DMA1DA uint16_t
#define TYPE_DMA1DAL uint16_t
#define TYPE_DMA1SA uint16_t
#define TYPE_DMA1SAL uint16_t
#define TYPE_DMA1SZ uint16_t
#define TYPE_DMA2CTL uint16_t
#define TYPE_DMA2CTL_H uint8_t
#define TYPE_DMA2CTL_L uint8_t
#define TYPE_DMA2DA uint16_t
#define TYPE_DMA2DAL uint16_t
#define TYPE_DMA2SA uint16_t
#define TYPE_DMA2SAL uint16_t
#define TYPE_DMA2SZ uint16_t
#define TYPE_DMA3CTL uint16_t
#define TYPE_DMA3CTL_H uint8_t
#define TYPE_DMA3CTL_L uint8_t
#define TYPE_DMA3SZ uint16_t
#define TYPE_DMA4CTL uint16_t
#define TYPE_DMA4CTL_H uint8_t
#define TYPE_DMA4CTL_L uint8_t
#define TYPE_DMA4SZ uint16_t
#define TYPE_DMA5CTL uint16_t
#define TYPE_DMA5CTL_H uint8_t
#define TYPE_DMA5CTL_L uint8_t
#define TYPE_DMA5SZ uint16_t
#define TYPE_DMACTL0 uint16_t
#define TYPE_DMACTL0_H uint8_t
#define TYPE_DMACTL0_L uint8_t
#define TYPE_DMACTL1 uint16_t
#define TYPE_DMACTL1_H uint8_t
#define TYPE_DMACTL1_L uint8_t
#define TYPE_DMACTL2 uint16_t
#define TYPE_DMACTL2_H uint8_t
#define TYPE_DMACTL2_L uint8_t
#define TYPE_DMACTL3 uint16_t
#define TYPE_DMACTL3_H uint8_t
#define TYPE_DMACTL3_L uint8_t
#define TYPE_DMACTL4 uint16_t
#define TYPE_DMACTL4_H uint8_t
#define TYPE_DMACTL4_L uint8_t
#define TYPE_DMAIV uint16_t
#define TYPE_DMAIV_H uint8_t
#define TYPE_DMAIV_L uint8_t
#define TYPE_EPCTL uint8_t
#define TYPE_ESPCTL uint16_t
#define TYPE_FCTL1 uint16_t
#define TYPE_FCTL1_H uint8_t
#define TYPE_FCTL1_L uint8_t
#define TYPE_FCTL2 uint16_t
#define TYPE_FCTL3 uint16_t
#define TYPE_FCTL3_H uint8_t
#define TYPE_FCTL3_L uint8_t
#define TYPE_FCTL4 uint16_t
#define TYPE_FCTL4_H uint8_t
#define TYPE_FCTL4_L uint8_t
#define TYPE_FLL_CTL0 uint8_t
#define TYPE_FLL_CTL1 uint8_t
#define TYPE_FLL_CTL2 uint8_t
#define TYPE_I2CDCTL uint8_t
#define TYPE_I2CDR uint8_t
#define TYPE_I2CDRB uint8_t
#define TYPE_I2CDRW uint16_t
#define TYPE_I2CIE uint8_t
#define TYPE_I2CIFG uint8_t
#define TYPE_I2CIV uint16_t
#define TYPE_I2CNDAT uint8_t
#define TYPE_I2COA uint16_t
#define TYPE_I2CPSC uint8_t
#define TYPE_I2CSA uint16_t
#define TYPE_I2CSCLH uint8_t
#define TYPE_I2CSCLL uint8_t
#define TYPE_I2CTCTL uint8_t
#define TYPE_IE1 uint8_t
#define TYPE_IE2 uint8_t
#define TYPE_IFG1 uint8_t
#define TYPE_IFG2 uint8_t
#define TYPE_LCDACTL uint8_t
#define TYPE_LCDAPCTL0 uint8_t
#define TYPE_LCDAPCTL1 uint8_t
#define TYPE_LCDAVCTL0 uint8_t
#define TYPE_LCDAVCTL1 uint8_t
#define TYPE_LCDBBLKCTL uint16_t
#define TYPE_LCDBBLKCTL_H uint8_t
#define TYPE_LCDBBLKCTL_L uint8_t
#define TYPE_LCDBCPCTL uint16_t
#define TYPE_LCDBCPCTL_H uint8_t
#define TYPE_LCDBCPCTL_L uint8_t
#define TYPE_LCDBCTL0 uint16_t
#define TYPE_LCDBCTL0_H uint8_t
#define TYPE_LCDBCTL0_L uint8_t
#define TYPE_LCDBCTL1 uint16_t
#define TYPE_LCDBCTL1_H uint8_t
#define TYPE_LCDBCTL1_L uint8_t
#define TYPE_LCDBIV uint16_t
#define TYPE_LCDBM1 uint8_t
#define TYPE_LCDBM10 uint8_t
#define TYPE_LCDBM11 uint8_t
#define TYPE_LCDBM12 uint8_t
#define TYPE_LCDBM13 uint8_t
#define TYPE_LCDBM14 uint8_t
#define TYPE_LCDBM15 uint8_t
#define TYPE_LCDBM16 uint8_t
#define TYPE_LCDBM17 uint8_t
#define TYPE_LCDBM18 uint8_t
#define TYPE_LCDBM19 uint8_t
#define TYPE_LCDBM2 uint8_t
#define TYPE_LCDBM20 uint8_t
#define TYPE_LCDBM21 uint8_t
#define TYPE_LCDBM22 uint8_t
#define TYPE_LCDBM23 uint8_t
#define TYPE_LCDBM24 uint8_t
#define TYPE_LCDBM3 uint8_t
#define TYPE_LCDBM4 uint8_t
#define TYPE_LCDBM5 uint8_t
#define TYPE_LCDBM6 uint8_t
#define TYPE_LCDBM7 uint8_t
#define TYPE_LCDBM8 uint8_t
#define TYPE_LCDBM9 uint8_t
#define TYPE_LCDBMEMCTL uint16_t
#define TYPE_LCDBMEMCTL_H uint8_t
#define TYPE_LCDBMEMCTL_L uint8_t
#define TYPE_LCDBPCTL0 uint16_t
#define TYPE_LCDBPCTL0_H uint8_t
#define TYPE_LCDBPCTL0_L uint8_t
#define TYPE_LCDBPCTL1 uint16_t
#define TYPE_LCDBPCTL1_H uint8_t
#define TYPE_LCDBPCTL1_L uint8_t
#define TYPE_LCDBPCTL2 uint16_t
#define TYPE_LCDBPCTL2_H uint8_t
#define TYPE_LCDBPCTL2_L uint8_t
#define TYPE_LCDBPCTL3 uint16_t
#define TYPE_LCDBPCTL3_H uint8_t
#define TYPE_LCDBPCTL3_L uint8_t
#define TYPE_LCDBVCTL uint16_t
#define TYPE_LCDBVCTL_H uint8_t
#define TYPE_LCDBVCTL_L uint8_t
#define TYPE_LCDCTL uint8_t
#define TYPE_LCDM1 uint8_t
#define TYPE_LCDM10 uint8_t
#define TYPE_LCDM11 uint8_t
#define TYPE_LCDM12 uint8_t
#define TYPE_LCDM13 uint8_t
#define TYPE_LCDM14 uint8_t
#define TYPE_LCDM15 uint8_t
#define TYPE_LCDM16 uint8_t
#define TYPE_LCDM17 uint8_t
#define TYPE_LCDM18 uint8_t
#define TYPE_LCDM19 uint8_t
#define TYPE_LCDM2 uint8_t
#define TYPE_LCDM20 uint8_t
#define TYPE_LCDM21 uint8_t
#define TYPE_LCDM22 uint8_t
#define TYPE_LCDM23 uint8_t
#define TYPE_LCDM24 uint8_t
#define TYPE_LCDM3 uint8_t
#define TYPE_LCDM4 uint8_t
#define TYPE_LCDM5 uint8_t
#define TYPE_LCDM6 uint8_t
#define TYPE_LCDM7 uint8_t
#define TYPE_LCDM8 uint8_t
#define TYPE_LCDM9 uint8_t
#define TYPE_LCDMA uint8_t
#define TYPE_LCDMB uint8_t
#define TYPE_LCDMC uint8_t
#define TYPE_LCDMD uint8_t
#define TYPE_LCDME uint8_t
#define TYPE_LCDMF uint8_t
#define TYPE_MAC uint16_t
#define TYPE_MAC32H uint16_t
#define TYPE_MAC32H_B uint8_t
#define TYPE_MAC32H_H uint8_t
#define TYPE_MAC32H_L uint8_t
#define TYPE_MAC32L uint16_t
#define TYPE_MAC32L_B uint8_t
#define TYPE_MAC32L_H uint8_t
#define TYPE_MAC32L_L uint8_t
#define TYPE_MACS uint16_t
#define TYPE_MACS32H uint16_t
#define TYPE_MACS32H_B uint8_t
#define TYPE_MACS32H_H uint8_t
#define TYPE_MACS32H_L uint8_t
#define TYPE_MACS32L uint16_t
#define TYPE_MACS32L_B uint8_t
#define TYPE_MACS32L_H uint8_t
#define TYPE_MACS32L_L uint8_t
#define TYPE_MACS_B uint8_t
#define TYPE_MACS_H uint8_t
#define TYPE_MACS_L uint8_t
#define TYPE_MAC_B uint8_t
#define TYPE_MAC_H uint8_t
#define TYPE_MAC_L uint8_t
#define TYPE_MBCTL uint16_t
#define TYPE_MBIN0 uint16_t
#define TYPE_MBIN1 uint16_t
#define TYPE_MBOUT0 uint16_t
#define TYPE_MBOUT1 uint16_t
#define TYPE_ME1 uint8_t
#define TYPE_ME2 uint8_t
#define TYPE_MPY uint16_t
#define TYPE_MPY32CTL0 uint16_t
#define TYPE_MPY32CTL0_H uint8_t
#define TYPE_MPY32CTL0_L uint8_t
#define TYPE_MPY32H uint16_t
#define TYPE_MPY32H_B uint8_t
#define TYPE_MPY32H_H uint8_t
#define TYPE_MPY32H_L uint8_t
#define TYPE_MPY32L uint16_t
#define TYPE_MPY32L_B uint8_t
#define TYPE_MPY32L_H uint8_t
#define TYPE_MPY32L_L uint8_t
#define TYPE_MPYS uint16_t
#define TYPE_MPYS32H uint16_t
#define TYPE_MPYS32H_B uint8_t
#define TYPE_MPYS32H_H uint8_t
#define TYPE_MPYS32H_L uint8_t
#define TYPE_MPYS32L uint16_t
#define TYPE_MPYS32L_B uint8_t
#define TYPE_MPYS32L_H uint8_t
#define TYPE_MPYS32L_L uint8_t
#define TYPE_MPYS_B uint8_t
#define TYPE_MPYS_H uint8_t
#define TYPE_MPYS_L uint8_t
#define TYPE_MPY_B uint8_t
#define TYPE_MPY_H uint8_t
#define TYPE_MPY_L uint8_t
#define TYPE_OA0CTL0 uint8_t
#define TYPE_OA0CTL1 uint8_t
#define TYPE_OA1CTL0 uint8_t
#define TYPE_OA1CTL1 uint8_t
#define TYPE_OA2CTL0 uint8_t
#define TYPE_OA2CTL1 uint8_t
#define TYPE_OASWCTL0 uint16_t
#define TYPE_OASWCTL0H uint8_t
#define TYPE_OASWCTL0L uint8_t
#define TYPE_OP2 uint16_t
#define TYPE_OP2H uint16_t
#define TYPE_OP2H_B uint8_t
#define TYPE_OP2H_H uint8_t
#define TYPE_OP2H_L uint8_t
#define TYPE_OP2L uint16_t
#define TYPE_OP2L_B uint8_t
#define TYPE_OP2L_H uint8_t
#define TYPE_OP2L_L uint8_t
#define TYPE_OP2_B uint8_t
#define TYPE_OP2_H uint8_t
#define TYPE_OP2_L uint8_t
#define TYPE_P0DIR uint8_t
#define TYPE_P0IE uint8_t
#define TYPE_P0IES uint8_t
#define TYPE_P0IFG uint8_t
#define TYPE_P0IN uint8_t
#define TYPE_P0OUT uint8_t
#define TYPE_P10DIR uint8_t
#define TYPE_P10IN uint8_t
#define TYPE_P10OUT uint8_t
#define TYPE_P10REN uint8_t
#define TYPE_P10SEL uint8_t
#define TYPE_P1DIR uint8_t
#define TYPE_P1IE uint8_t
#define TYPE_P1IES uint8_t
#define TYPE_P1IFG uint8_t
#define TYPE_P1IN uint8_t
#define TYPE_P1IV uint16_t
#define TYPE_P1MAP01 uint16_t
#define TYPE_P1MAP01_H uint8_t
#define TYPE_P1MAP01_L uint8_t
#define TYPE_P1MAP23 uint16_t
#define TYPE_P1MAP23_H uint8_t
#define TYPE_P1MAP23_L uint8_t
#define TYPE_P1MAP45 uint16_t
#define TYPE_P1MAP45_H uint8_t
#define TYPE_P1MAP45_L uint8_t
#define TYPE_P1MAP67 uint16_t
#define TYPE_P1MAP67_H uint8_t
#define TYPE_P1MAP67_L uint8_t
#define TYPE_P1OUT uint8_t
#define TYPE_P1REN uint8_t
#define TYPE_P1SEL uint8_t
#define TYPE_P1SEL2 uint8_t
#define TYPE_P2DIR uint8_t
#define TYPE_P2IE uint8_t
#define TYPE_P2IES uint8_t
#define TYPE_P2IFG uint8_t
#define TYPE_P2IN uint8_t
#define TYPE_P2IV uint16_t
#define TYPE_P2MAP01 uint16_t
#define TYPE_P2MAP01_H uint8_t
#define TYPE_P2MAP01_L uint8_t
#define TYPE_P2MAP23 uint16_t
#define TYPE_P2MAP23_H uint8_t
#define TYPE_P2MAP23_L uint8_t
#define TYPE_P2MAP45 uint16_t
#define TYPE_P2MAP45_H uint8_t
#define TYPE_P2MAP45_L uint8_t
#define TYPE_P2MAP67 uint16_t
#define TYPE_P2MAP67_H uint8_t
#define TYPE_P2MAP67_L uint8_t
#define TYPE_P2OUT uint8_t
#define TYPE_P2REN uint8_t
#define TYPE_P2SEL uint8_t
#define TYPE_P2SEL2 uint8_t
#define TYPE_P3DIR uint8_t
#define TYPE_P3IN uint8_t
#define TYPE_P3IV uint16_t
#define TYPE_P3MAP01 uint16_t
#define TYPE_P3MAP01_H uint8_t
#define TYPE_P3MAP01_L uint8_t
#define TYPE_P3MAP23 uint16_t
#define TYPE_P3MAP23_H uint8_t
#define TYPE_P3MAP23_L uint8_t
#define TYPE_P3MAP45 uint16_t
#define TYPE_P3MAP45_H uint8_t
#define TYPE_P3MAP45_L uint8_t
#define TYPE_P3MAP67 uint16_t
#define TYPE_P3MAP67_H uint8_t
#define TYPE_P3MAP67_L uint8_t
#define TYPE_P3OUT uint8_t
#define TYPE_P3REN uint8_t
#define TYPE_P3SEL uint8_t
#define TYPE_P4DIR uint8_t
#define TYPE_P4IN uint8_t
#define TYPE_P4IV uint16_t
#define TYPE_P4MAP01 uint16_t
#define TYPE_P4MAP01_H uint8_t
#define TYPE_P4MAP01_L uint8_t
#define TYPE_P4MAP23 uint16_t
#define TYPE_P4MAP23_H uint8_t
#define TYPE_P4MAP23_L uint8_t
#define TYPE_P4MAP45 uint16_t
#define TYPE_P4MAP45_H uint8_t
#define TYPE_P4MAP45_L uint8_t
#define TYPE_P4MAP67 uint16_t
#define TYPE_P4MAP67_H uint8_t
#define TYPE_P4MAP67_L uint8_t
#define TYPE_P4OUT uint8_t
#define TYPE_P4REN uint8_t
#define TYPE_P4SEL uint8_t
#define TYPE_P5DIR uint8_t
#define TYPE_P5IN uint8_t
#define TYPE_P5OUT uint8_t
#define TYPE_P5REN uint8_t
#define TYPE_P5SEL uint8_t
#define TYPE_P6DIR uint8_t
#define TYPE_P6IN uint8_t
#define TYPE_P6OUT uint8_t
#define TYPE_P6REN uint8_t
#define TYPE_P6SEL uint8_t
#define TYPE_P7DIR uint8_t
#define TYPE_P7IN uint8_t
#define TYPE_P7OUT uint8_t
#define TYPE_P7REN uint8_t
#define TYPE_P7SEL uint8_t
#define TYPE_P8DIR uint8_t
#define TYPE_P8IN uint8_t
#define TYPE_P8OUT uint8_t
#define TYPE_P8REN uint8_t
#define TYPE_P8SEL uint8_t
#define TYPE_P9DIR uint8_t
#define TYPE_P9IN uint8_t
#define TYPE_P9OUT uint8_t
#define TYPE_P9REN uint8_t
#define TYPE_P9SEL uint8_t
#define TYPE_PADIR uint16_t
#define TYPE_PADIR_H uint8_t
#define TYPE_PADIR_L uint8_t
#define TYPE_PADS uint16_t
#define TYPE_PADS_H uint8_t
#define TYPE_PADS_L uint8_t
#define TYPE_PAIE uint16_t
#define TYPE_PAIES uint16_t
#define TYPE_PAIES_H uint8_t
#define TYPE_PAIES_L uint8_t
#define TYPE_PAIE_H uint8_t
#define TYPE_PAIE_L uint8_t
#define TYPE_PAIFG uint16_t
#define TYPE_PAIFG_H uint8_t
#define TYPE_PAIFG_L uint8_t
#define TYPE_PAIN uint8_t
#define TYPE_PAOUT uint16_t
#define TYPE_PAOUT_H uint8_t
#define TYPE_PAOUT_L uint8_t
#define TYPE_PAREN uint16_t
#define TYPE_PAREN_H uint8_t
#define TYPE_PAREN_L uint8_t
#define TYPE_PASEL uint16_t
#define TYPE_PASEL0 uint16_t
#define TYPE_PASEL0_H uint8_t
#define TYPE_PASEL0_L uint8_t
#define TYPE_PASEL1 uint16_t
#define TYPE_PASEL1_H uint8_t
#define TYPE_PASEL1_L uint8_t
#define TYPE_PASEL_H uint8_t
#define TYPE_PASEL_L uint8_t
#define TYPE_PBDIR uint16_t
#define TYPE_PBDIR_H uint8_t
#define TYPE_PBDIR_L uint8_t
#define TYPE_PBDS uint16_t
#define TYPE_PBDS_H uint8_t
#define TYPE_PBDS_L uint8_t
#define TYPE_PBIE uint16_t
#define TYPE_PBIES uint16_t
#define TYPE_PBIES_H uint8_t
#define TYPE_PBIES_L uint8_t
#define TYPE_PBIE_H uint8_t
#define TYPE_PBIE_L uint8_t
#define TYPE_PBIFG uint16_t
#define TYPE_PBIFG_H uint8_t
#define TYPE_PBIFG_L uint8_t
#define TYPE_PBIN uint8_t
#define TYPE_PBOUT uint16_t
#define TYPE_PBOUT_H uint8_t
#define TYPE_PBOUT_L uint8_t
#define TYPE_PBREN uint16_t
#define TYPE_PBREN_H uint8_t
#define TYPE_PBREN_L uint8_t
#define TYPE_PBSEL uint16_t
#define TYPE_PBSEL_H uint8_t
#define TYPE_PBSEL_L uint8_t
#define TYPE_PCDIR uint16_t
#define TYPE_PCDIR_H uint8_t
#define TYPE_PCDIR_L uint8_t
#define TYPE_PCDS uint16_t
#define TYPE_PCDS_H uint8_t
#define TYPE_PCDS_L uint8_t
#define TYPE_PCOUT uint16_t
#define TYPE_PCOUT_H uint8_t
#define TYPE_PCOUT_L uint8_t
#define TYPE_PCREN uint16_t
#define TYPE_PCREN_H uint8_t
#define TYPE_PCREN_L uint8_t
#define TYPE_PCSEL uint16_t
#define TYPE_PCSEL_H uint8_t
#define TYPE_PCSEL_L uint8_t
#define TYPE_PDDIR uint16_t
#define TYPE_PDDIR_H uint8_t
#define TYPE_PDDIR_L uint8_t
#define TYPE_PDDS uint16_t
#define TYPE_PDDS_H uint8_t
#define TYPE_PDDS_L uint8_t
#define TYPE_PDOUT uint16_t
#define TYPE_PDOUT_H uint8_t
#define TYPE_PDOUT_L uint8_t
#define TYPE_PDREN uint16_t
#define TYPE_PDREN_H uint8_t
#define TYPE_PDREN_L uint8_t
#define TYPE_PDSEL uint16_t
#define TYPE_PDSEL_H uint8_t
#define TYPE_PDSEL_L uint8_t
#define TYPE_PEDIR uint16_t
#define TYPE_PEDIR_H uint8_t
#define TYPE_PEDIR_L uint8_t
#define TYPE_PEDS uint16_t
#define TYPE_PEDS_H uint8_t
#define TYPE_PEDS_L uint8_t
#define TYPE_PEOUT uint16_t
#define TYPE_PEOUT_H uint8_t
#define TYPE_PEOUT_L uint8_t
#define TYPE_PEREN uint16_t
#define TYPE_PEREN_H uint8_t
#define TYPE_PEREN_L uint8_t
#define TYPE_PESEL uint16_t
#define TYPE_PESEL_H uint8_t
#define TYPE_PESEL_L uint8_t
#define TYPE_PFDIR uint16_t
#define TYPE_PFDIR_H uint8_t
#define TYPE_PFDIR_L uint8_t
#define TYPE_PFDS uint16_t
#define TYPE_PFDS_H uint8_t
#define TYPE_PFDS_L uint8_t
#define TYPE_PFOUT uint16_t
#define TYPE_PFOUT_H uint8_t
#define TYPE_PFOUT_L uint8_t
#define TYPE_PFREN uint16_t
#define TYPE_PFREN_H uint8_t
#define TYPE_PFREN_L uint8_t
#define TYPE_PFSEL uint16_t
#define TYPE_PFSEL_H uint8_t
#define TYPE_PFSEL_L uint8_t
#define TYPE_PJDIR uint16_t
#define TYPE_PJDIR_H uint8_t
#define TYPE_PJDIR_L uint8_t
#define TYPE_PJDS uint16_t
#define TYPE_PJDS_H uint8_t
#define TYPE_PJDS_L uint8_t
#define TYPE_PJOUT uint16_t
#define TYPE_PJOUT_H uint8_t
#define TYPE_PJOUT_L uint8_t
#define TYPE_PJREN uint16_t
#define TYPE_PJREN_H uint8_t
#define TYPE_PJREN_L uint8_t
#define TYPE_PJSEL uint16_t
#define TYPE_PJSEL_H uint8_t
#define TYPE_PJSEL_L uint8_t
#define TYPE_PM5CTL0 uint16_t
#define TYPE_PM5CTL0_H uint8_t
#define TYPE_PM5CTL0_L uint8_t
#define TYPE_PMAPCTL uint16_t
#define TYPE_PMAPCTL_H uint8_t
#define TYPE_PMAPCTL_L uint8_t
#define TYPE_PMAPKEYID uint16_t
#define TYPE_PMAPKEYID_H uint8_t
#define TYPE_PMAPKEYID_L uint8_t
#define TYPE_PMMCTL0 uint16_t
#define TYPE_PMMCTL0_H uint8_t
#define TYPE_PMMCTL0_L uint8_t
#define TYPE_PMMCTL1 uint16_t
#define TYPE_PMMCTL1_H uint8_t
#define TYPE_PMMCTL1_L uint8_t
#define TYPE_PMMIFG uint16_t
#define TYPE_PMMIFG_H uint8_t
#define TYPE_PMMIFG_L uint8_t
#define TYPE_PMMRIE uint16_t
#define TYPE_PMMRIE_H uint8_t
#define TYPE_PMMRIE_L uint8_t
#define TYPE_PORT_DIR uint8_t
#define TYPE_PORT_IN uint8_t
#define TYPE_PORT_OUT uint8_t
#define TYPE_PORT_REN uint8_t
#define TYPE_PORT_SEL uint8_t
#define TYPE_RCCTL0 uint16_t
#define TYPE_RCCTL0_H uint8_t
#define TYPE_RCCTL0_L uint8_t
#define TYPE_REFCTL0 uint16_t
#define TYPE_REFCTL0_H uint8_t
#define TYPE_REFCTL0_L uint8_t
#define TYPE_RES0 uint16_t
#define TYPE_RES0_H uint8_t
#define TYPE_RES0_L uint8_t
#define TYPE_RES1 uint16_t
#define TYPE_RES1_H uint8_t
#define TYPE_RES1_L uint8_t
#define TYPE_RES2 uint16_t
#define TYPE_RES2_H uint8_t
#define TYPE_RES2_L uint8_t
#define TYPE_RES3 uint16_t
#define TYPE_RES3_H uint8_t
#define TYPE_RES3_L uint8_t
#define TYPE_RESHI uint16_t
#define TYPE_RESHI_H uint8_t
#define TYPE_RESHI_L uint8_t
#define TYPE_RESLO uint16_t
#define TYPE_RESLO_H uint8_t
#define TYPE_RESLO_L uint8_t
#define TYPE_RET0 uint16_t
#define TYPE_RET1 uint16_t
#define TYPE_RET10 uint16_t
#define TYPE_RET11 uint16_t
#define TYPE_RET12 uint16_t
#define TYPE_RET13 uint16_t
#define TYPE_RET14 uint16_t
#define TYPE_RET15 uint16_t
#define TYPE_RET16 uint16_t
#define TYPE_RET17 uint16_t
#define TYPE_RET18 uint16_t
#define TYPE_RET19 uint16_t
#define TYPE_RET2 uint16_t
#define TYPE_RET20 uint16_t
#define TYPE_RET21 uint16_t
#define TYPE_RET22 uint16_t
#define TYPE_RET23 uint16_t
#define TYPE_RET24 uint16_t
#define TYPE_RET25 uint16_t
#define TYPE_RET26 uint16_t
#define TYPE_RET27 uint16_t
#define TYPE_RET28 uint16_t
#define TYPE_RET29 uint16_t
#define TYPE_RET3 uint16_t
#define TYPE_RET30 uint16_t
#define TYPE_RET31 uint16_t
#define TYPE_RET4 uint16_t
#define TYPE_RET5 uint16_t
#define TYPE_RET6 uint16_t
#define TYPE_RET7 uint16_t
#define TYPE_RET8 uint16_t
#define TYPE_RET9 uint16_t
#define TYPE_RF1ADINW uint16_t
#define TYPE_RF1ADINW_H uint8_t
#define TYPE_RF1ADINW_L uint8_t
#define TYPE_RF1ADOUT0W uint16_t
#define TYPE_RF1ADOUT0W_H uint8_t
#define TYPE_RF1ADOUT0W_L uint8_t
#define TYPE_RF1ADOUT1W uint16_t
#define TYPE_RF1ADOUT1W_H uint8_t
#define TYPE_RF1ADOUT1W_L uint8_t
#define TYPE_RF1ADOUT2W uint16_t
#define TYPE_RF1ADOUT2W_H uint8_t
#define TYPE_RF1ADOUT2W_L uint8_t
#define TYPE_RF1AIE uint16_t
#define TYPE_RF1AIES uint16_t
#define TYPE_RF1AIES_H uint8_t
#define TYPE_RF1AIES_L uint8_t
#define TYPE_RF1AIE_H uint8_t
#define TYPE_RF1AIE_L uint8_t
#define TYPE_RF1AIFCTL0 uint16_t
#define TYPE_RF1AIFCTL0_H uint8_t
#define TYPE_RF1AIFCTL0_L uint8_t
#define TYPE_RF1AIFCTL1 uint16_t
#define TYPE_RF1AIFCTL1_H uint8_t
#define TYPE_RF1AIFCTL1_L uint8_t
#define TYPE_RF1AIFCTL2 uint16_t
#define TYPE_RF1AIFCTL2_H uint8_t
#define TYPE_RF1AIFCTL2_L uint8_t
#define TYPE_RF1AIFERR uint16_t
#define TYPE_RF1AIFERRV uint16_t
#define TYPE_RF1AIFERRV_H uint8_t
#define TYPE_RF1AIFERRV_L uint8_t
#define TYPE_RF1AIFERR_H uint8_t
#define TYPE_RF1AIFERR_L uint8_t
#define TYPE_RF1AIFG uint16_t
#define TYPE_RF1AIFG_H uint8_t
#define TYPE_RF1AIFG_L uint8_t
#define TYPE_RF1AIFIV uint16_t
#define TYPE_RF1AIFIV_H uint8_t
#define TYPE_RF1AIFIV_L uint8_t
#define TYPE_RF1AIN uint16_t
#define TYPE_RF1AINSTR1W uint16_t
#define TYPE_RF1AINSTR1W_H uint8_t
#define TYPE_RF1AINSTR1W_L uint8_t
#define TYPE_RF1AINSTR2W uint16_t
#define TYPE_RF1AINSTR2W_H uint8_t
#define TYPE_RF1AINSTR2W_L uint8_t
#define TYPE_RF1AINSTRW uint16_t
#define TYPE_RF1AINSTRW_H uint8_t
#define TYPE_RF1AINSTRW_L uint8_t
#define TYPE_RF1AIN_H uint8_t
#define TYPE_RF1AIN_L uint8_t
#define TYPE_RF1AIV uint16_t
#define TYPE_RF1AIV_H uint8_t
#define TYPE_RF1AIV_L uint8_t
#define TYPE_RF1ARXFIFO uint16_t
#define TYPE_RF1ARXFIFO_H uint8_t
#define TYPE_RF1ARXFIFO_L uint8_t
#define TYPE_RF1ASTAT0W uint16_t
#define TYPE_RF1ASTAT0W_H uint8_t
#define TYPE_RF1ASTAT0W_L uint8_t
#define TYPE_RF1ASTAT1W uint16_t
#define TYPE_RF1ASTAT1W_H uint8_t
#define TYPE_RF1ASTAT1W_L uint8_t
#define TYPE_RF1ASTAT2W uint16_t
#define TYPE_RF1ASTAT2W_H uint8_t
#define TYPE_RF1ASTAT2W_L uint8_t
#define TYPE_RF1ATXFIFO uint16_t
#define TYPE_RF1ATXFIFO_H uint8_t
#define TYPE_RF1ATXFIFO_L uint8_t
#define TYPE_RT0PS uint8_t
#define TYPE_RT1PS uint8_t
#define TYPE_RTCADOWDAY uint16_t
#define TYPE_RTCADOWDAY_H uint8_t
#define TYPE_RTCADOWDAY_L uint8_t
#define TYPE_RTCAMINHR uint16_t
#define TYPE_RTCAMINHR_H uint8_t
#define TYPE_RTCAMINHR_L uint8_t
#define TYPE_RTCCTL uint8_t
#define TYPE_RTCCTL01 uint16_t
#define TYPE_RTCCTL01_H uint8_t
#define TYPE_RTCCTL01_L uint8_t
#define TYPE_RTCCTL23 uint16_t
#define TYPE_RTCCTL23_H uint8_t
#define TYPE_RTCCTL23_L uint8_t
#define TYPE_RTCDATE uint16_t
#define TYPE_RTCDATE_H uint8_t
#define TYPE_RTCDATE_L uint8_t
#define TYPE_RTCDAY uint8_t
#define TYPE_RTCDOW uint8_t
#define TYPE_RTCHOUR uint8_t
#define TYPE_RTCIV uint16_t
#define TYPE_RTCMIN uint8_t
#define TYPE_RTCMON uint8_t
#define TYPE_RTCNT1 uint8_t
#define TYPE_RTCNT12 uint16_t
#define TYPE_RTCNT2 uint8_t
#define TYPE_RTCNT3 uint8_t
#define TYPE_RTCNT34 uint16_t
#define TYPE_RTCNT4 uint8_t
#define TYPE_RTCPS uint16_t
#define TYPE_RTCPS0CTL uint16_t
#define TYPE_RTCPS0CTL_H uint8_t
#define TYPE_RTCPS0CTL_L uint8_t
#define TYPE_RTCPS1CTL uint16_t
#define TYPE_RTCPS1CTL_H uint8_t
#define TYPE_RTCPS1CTL_L uint8_t
#define TYPE_RTCPS_H uint8_t
#define TYPE_RTCPS_L uint8_t
#define TYPE_RTCSEC uint8_t
#define TYPE_RTCTIM0 uint16_t
#define TYPE_RTCTIM0_H uint8_t
#define TYPE_RTCTIM0_L uint8_t
#define TYPE_RTCTIM1 uint16_t
#define TYPE_RTCTIM1_H uint8_t
#define TYPE_RTCTIM1_L uint8_t
#define TYPE_RTCTL uint8_t
#define TYPE_RTCYEAR uint16_t
#define TYPE_RTCYEARH uint8_t
#define TYPE_RTCYEARL uint8_t
#define TYPE_RTCYEAR_H uint8_t
#define TYPE_RTCYEAR_L uint8_t
#define TYPE_RXBUF uint8_t
#define TYPE_RXBUF0 uint8_t
#define TYPE_RXBUF1 uint8_t
#define TYPE_RXBUF_0 uint8_t
#define TYPE_RXBUF_1 uint8_t
#define TYPE_SCFI0 uint8_t
#define TYPE_SCFI1 uint8_t
#define TYPE_SCFQCTL uint8_t
#define TYPE_SD16AE uint8_t
#define TYPE_SD16CCTL0 uint16_t
#define TYPE_SD16CCTL1 uint16_t
#define TYPE_SD16CCTL2 uint16_t
#define TYPE_SD16CCTL3 uint16_t
#define TYPE_SD16CCTL4 uint16_t
#define TYPE_SD16CCTL5 uint16_t
#define TYPE_SD16CCTL6 uint16_t
#define TYPE_SD16CONF0 uint8_t
#define TYPE_SD16CONF1 uint8_t
#define TYPE_SD16CTL uint16_t
#define TYPE_SD16INCTL0 uint8_t
#define TYPE_SD16INCTL1 uint8_t
#define TYPE_SD16INCTL2 uint8_t
#define TYPE_SD16INCTL3 uint8_t
#define TYPE_SD16INCTL4 uint8_t
#define TYPE_SD16INCTL5 uint8_t
#define TYPE_SD16INCTL6 uint8_t
#define TYPE_SD16IV uint16_t
#define TYPE_SD16MEM0 uint16_t
#define TYPE_SD16MEM1 uint16_t
#define TYPE_SD16MEM2 uint16_t
#define TYPE_SD16MEM3 uint16_t
#define TYPE_SD16MEM4 uint16_t
#define TYPE_SD16MEM5 uint16_t
#define TYPE_SD16MEM6 uint16_t
#define TYPE_SD16PRE0 uint8_t
#define TYPE_SD16PRE1 uint8_t
#define TYPE_SD16PRE2 uint8_t
#define TYPE_SD16PRE3 uint8_t
#define TYPE_SD16PRE4 uint8_t
#define TYPE_SD16PRE5 uint8_t
#define TYPE_SD16PRE6 uint8_t
#define TYPE_SFRIE1 uint16_t
#define TYPE_SFRIE1_H uint8_t
#define TYPE_SFRIE1_L uint8_t
#define TYPE_SFRIFG1 uint16_t
#define TYPE_SFRIFG1_H uint8_t
#define TYPE_SFRIFG1_L uint8_t
#define TYPE_SFRRPCR uint16_t
#define TYPE_SFRRPCR_H uint8_t
#define TYPE_SFRRPCR_L uint8_t
#define TYPE_SIFCNT uint16_t
#define TYPE_SIFCTL0 uint16_t
#define TYPE_SIFCTL1 uint16_t
#define TYPE_SIFCTL2 uint16_t
#define TYPE_SIFCTL3 uint16_t
#define TYPE_SIFCTL4 uint16_t
#define TYPE_SIFCTL5 uint16_t
#define TYPE_SIFDACR0 uint16_t
#define TYPE_SIFDACR1 uint16_t
#define TYPE_SIFDACR2 uint16_t
#define TYPE_SIFDACR3 uint16_t
#define TYPE_SIFDACR4 uint16_t
#define TYPE_SIFDACR5 uint16_t
#define TYPE_SIFDACR6 uint16_t
#define TYPE_SIFDACR7 uint16_t
#define TYPE_SIFDEBUG uint16_t
#define TYPE_SIFPSMV uint16_t
#define TYPE_SIFTPSMV uint16_t
#define TYPE_SIFTSM0 uint16_t
#define TYPE_SIFTSM1 uint16_t
#define TYPE_SIFTSM10 uint16_t
#define TYPE_SIFTSM11 uint16_t
#define TYPE_SIFTSM12 uint16_t
#define TYPE_SIFTSM13 uint16_t
#define TYPE_SIFTSM14 uint16_t
#define TYPE_SIFTSM15 uint16_t
#define TYPE_SIFTSM16 uint16_t
#define TYPE_SIFTSM17 uint16_t
#define TYPE_SIFTSM18 uint16_t
#define TYPE_SIFTSM19 uint16_t
#define TYPE_SIFTSM2 uint16_t
#define TYPE_SIFTSM20 uint16_t
#define TYPE_SIFTSM21 uint16_t
#define TYPE_SIFTSM22 uint16_t
#define TYPE_SIFTSM23 uint16_t
#define TYPE_SIFTSM3 uint16_t
#define TYPE_SIFTSM4 uint16_t
#define TYPE_SIFTSM5 uint16_t
#define TYPE_SIFTSM6 uint16_t
#define TYPE_SIFTSM7 uint16_t
#define TYPE_SIFTSM8 uint16_t
#define TYPE_SIFTSM9 uint16_t
#define TYPE_SUMEXT uint16_t
#define TYPE_SVSCTL uint8_t
#define TYPE_SVSMHCTL uint16_t
#define TYPE_SVSMHCTL_H uint8_t
#define TYPE_SVSMHCTL_L uint8_t
#define TYPE_SVSMIO uint16_t
#define TYPE_SVSMIO_H uint8_t
#define TYPE_SVSMIO_L uint8_t
#define TYPE_SVSMLCTL uint16_t
#define TYPE_SVSMLCTL_H uint8_t
#define TYPE_SVSMLCTL_L uint8_t
#define TYPE_SWCTL uint8_t
#define TYPE_SYSBERRIV uint16_t
#define TYPE_SYSBERRIV_H uint8_t
#define TYPE_SYSBERRIV_L uint8_t
#define TYPE_SYSBSLC uint16_t
#define TYPE_SYSBSLC_H uint8_t
#define TYPE_SYSBSLC_L uint8_t
#define TYPE_SYSCNF uint16_t
#define TYPE_SYSCNF_H uint8_t
#define TYPE_SYSCNF_L uint8_t
#define TYPE_SYSCTL uint16_t
#define TYPE_SYSCTL_H uint8_t
#define TYPE_SYSCTL_L uint8_t
#define TYPE_SYSJMBC uint16_t
#define TYPE_SYSJMBC_H uint8_t
#define TYPE_SYSJMBC_L uint8_t
#define TYPE_SYSJMBI0 uint16_t
#define TYPE_SYSJMBI0_H uint8_t
#define TYPE_SYSJMBI0_L uint8_t
#define TYPE_SYSJMBI1 uint16_t
#define TYPE_SYSJMBI1_H uint8_t
#define TYPE_SYSJMBI1_L uint8_t
#define TYPE_SYSJMBO0 uint16_t
#define TYPE_SYSJMBO0_H uint8_t
#define TYPE_SYSJMBO0_L uint8_t
#define TYPE_SYSJMBO1 uint16_t
#define TYPE_SYSJMBO1_H uint8_t
#define TYPE_SYSJMBO1_L uint8_t
#define TYPE_SYSRSTIV uint16_t
#define TYPE_SYSRSTIV_H uint8_t
#define TYPE_SYSRSTIV_L uint8_t
#define TYPE_SYSSNIV uint16_t
#define TYPE_SYSSNIV_H uint8_t
#define TYPE_SYSSNIV_L uint8_t
#define TYPE_SYSUNIV uint16_t
#define TYPE_SYSUNIV_H uint8_t
#define TYPE_SYSUNIV_L uint8_t
#define TYPE_TA0CCR0 uint16_t
#define TYPE_TA0CCR0_H uint8_t
#define TYPE_TA0CCR0_L uint8_t
#define TYPE_TA0CCR1 uint16_t
#define TYPE_TA0CCR1_H uint8_t
#define TYPE_TA0CCR1_L uint8_t
#define TYPE_TA0CCR2 uint16_t
#define TYPE_TA0CCR2_H uint8_t
#define TYPE_TA0CCR2_L uint8_t
#define TYPE_TA0CCR3 uint16_t
#define TYPE_TA0CCR3_H uint8_t
#define TYPE_TA0CCR3_L uint8_t
#define TYPE_TA0CCR4 uint16_t
#define TYPE_TA0CCR4_H uint8_t
#define TYPE_TA0CCR4_L uint8_t
#define TYPE_TA0CCTL0 uint16_t
#define TYPE_TA0CCTL0_H uint8_t
#define TYPE_TA0CCTL0_L uint8_t
#define TYPE_TA0CCTL1 uint16_t
#define TYPE_TA0CCTL1_H uint8_t
#define TYPE_TA0CCTL1_L uint8_t
#define TYPE_TA0CCTL2 uint16_t
#define TYPE_TA0CCTL2_H uint8_t
#define TYPE_TA0CCTL2_L uint8_t
#define TYPE_TA0CCTL3 uint16_t
#define TYPE_TA0CCTL3_H uint8_t
#define TYPE_TA0CCTL3_L uint8_t
#define TYPE_TA0CCTL4 uint16_t
#define TYPE_TA0CCTL4_H uint8_t
#define TYPE_TA0CCTL4_L uint8_t
#define TYPE_TA0CTL uint16_t
#define TYPE_TA0CTL_H uint8_t
#define TYPE_TA0CTL_L uint8_t
#define TYPE_TA0EX0 uint16_t
#define TYPE_TA0EX0_H uint8_t
#define TYPE_TA0EX0_L uint8_t
#define TYPE_TA0IV uint16_t
#define TYPE_TA0IV_H uint8_t
#define TYPE_TA0IV_L uint8_t
#define TYPE_TA0R uint16_t
#define TYPE_TA0R_H uint8_t
#define TYPE_TA0R_L uint8_t
#define TYPE_TA1CCR0 uint16_t
#define TYPE_TA1CCR0_H uint8_t
#define TYPE_TA1CCR0_L uint8_t
#define TYPE_TA1CCR1 uint16_t
#define TYPE_TA1CCR1_H uint8_t
#define TYPE_TA1CCR1_L uint8_t
#define TYPE_TA1CCR2 uint16_t
#define TYPE_TA1CCR2_H uint8_t
#define TYPE_TA1CCR2_L uint8_t
#define TYPE_TA1CCR3 uint16_t
#define TYPE_TA1CCR4 uint16_t
#define TYPE_TA1CCTL0 uint16_t
#define TYPE_TA1CCTL0_H uint8_t
#define TYPE_TA1CCTL0_L uint8_t
#define TYPE_TA1CCTL1 uint16_t
#define TYPE_TA1CCTL1_H uint8_t
#define TYPE_TA1CCTL1_L uint8_t
#define TYPE_TA1CCTL2 uint16_t
#define TYPE_TA1CCTL2_H uint8_t
#define TYPE_TA1CCTL2_L uint8_t
#define TYPE_TA1CCTL3 uint16_t
#define TYPE_TA1CCTL4 uint16_t
#define TYPE_TA1CTL uint16_t
#define TYPE_TA1CTL_H uint8_t
#define TYPE_TA1CTL_L uint8_t
#define TYPE_TA1EX0 uint16_t
#define TYPE_TA1EX0_H uint8_t
#define TYPE_TA1EX0_L uint8_t
#define TYPE_TA1IV uint16_t
#define TYPE_TA1IV_H uint8_t
#define TYPE_TA1IV_L uint8_t
#define TYPE_TA1R uint16_t
#define TYPE_TA1R_H uint8_t
#define TYPE_TA1R_L uint8_t
#define TYPE_TA2CCR0 uint16_t
#define TYPE_TA2CCR0_H uint8_t
#define TYPE_TA2CCR0_L uint8_t
#define TYPE_TA2CCR1 uint16_t
#define TYPE_TA2CCR1_H uint8_t
#define TYPE_TA2CCR1_L uint8_t
#define TYPE_TA2CCR2 uint16_t
#define TYPE_TA2CCR2_H uint8_t
#define TYPE_TA2CCR2_L uint8_t
#define TYPE_TA2CCTL0 uint16_t
#define TYPE_TA2CCTL0_H uint8_t
#define TYPE_TA2CCTL0_L uint8_t
#define TYPE_TA2CCTL1 uint16_t
#define TYPE_TA2CCTL1_H uint8_t
#define TYPE_TA2CCTL1_L uint8_t
#define TYPE_TA2CCTL2 uint16_t
#define TYPE_TA2CCTL2_H uint8_t
#define TYPE_TA2CCTL2_L uint8_t
#define TYPE_TA2CTL uint16_t
#define TYPE_TA2CTL_H uint8_t
#define TYPE_TA2CTL_L uint8_t
#define TYPE_TA2EX0 uint16_t
#define TYPE_TA2EX0_H uint8_t
#define TYPE_TA2EX0_L uint8_t
#define TYPE_TA2IV uint16_t
#define TYPE_TA2IV_H uint8_t
#define TYPE_TA2IV_L uint8_t
#define TYPE_TA2R uint16_t
#define TYPE_TA2R_H uint8_t
#define TYPE_TA2R_L uint8_t
#define TYPE_TACCR0 uint16_t
#define TYPE_TACCR1 uint16_t
#define TYPE_TACCR2 uint16_t
#define TYPE_TACCR3 uint16_t
#define TYPE_TACCR4 uint16_t
#define TYPE_TACCTL0 uint16_t
#define TYPE_TACCTL1 uint16_t
#define TYPE_TACCTL2 uint16_t
#define TYPE_TACCTL3 uint16_t
#define TYPE_TACCTL4 uint16_t
#define TYPE_TACTL uint16_t
#define TYPE_TAIV uint16_t
#define TYPE_TAR uint16_t
#define TYPE_TAR1 uint16_t
#define TYPE_TB0CCR0 uint16_t
#define TYPE_TB0CCR0_H uint8_t
#define TYPE_TB0CCR0_L uint8_t
#define TYPE_TB0CCR1 uint16_t
#define TYPE_TB0CCR1_H uint8_t
#define TYPE_TB0CCR1_L uint8_t
#define TYPE_TB0CCR2 uint16_t
#define TYPE_TB0CCR2_H uint8_t
#define TYPE_TB0CCR2_L uint8_t
#define TYPE_TB0CCR3 uint16_t
#define TYPE_TB0CCR3_H uint8_t
#define TYPE_TB0CCR3_L uint8_t
#define TYPE_TB0CCR4 uint16_t
#define TYPE_TB0CCR4_H uint8_t
#define TYPE_TB0CCR4_L uint8_t
#define TYPE_TB0CCR5 uint16_t
#define TYPE_TB0CCR5_H uint8_t
#define TYPE_TB0CCR5_L uint8_t
#define TYPE_TB0CCR6 uint16_t
#define TYPE_TB0CCR6_H uint8_t
#define TYPE_TB0CCR6_L uint8_t
#define TYPE_TB0CCTL0 uint16_t
#define TYPE_TB0CCTL0_H uint8_t
#define TYPE_TB0CCTL0_L uint8_t
#define TYPE_TB0CCTL1 uint16_t
#define TYPE_TB0CCTL1_H uint8_t
#define TYPE_TB0CCTL1_L uint8_t
#define TYPE_TB0CCTL2 uint16_t
#define TYPE_TB0CCTL2_H uint8_t
#define TYPE_TB0CCTL2_L uint8_t
#define TYPE_TB0CCTL3 uint16_t
#define TYPE_TB0CCTL3_H uint8_t
#define TYPE_TB0CCTL3_L uint8_t
#define TYPE_TB0CCTL4 uint16_t
#define TYPE_TB0CCTL4_H uint8_t
#define TYPE_TB0CCTL4_L uint8_t
#define TYPE_TB0CCTL5 uint16_t
#define TYPE_TB0CCTL5_H uint8_t
#define TYPE_TB0CCTL5_L uint8_t
#define TYPE_TB0CCTL6 uint16_t
#define TYPE_TB0CCTL6_H uint8_t
#define TYPE_TB0CCTL6_L uint8_t
#define TYPE_TB0CTL uint16_t
#define TYPE_TB0CTL_H uint8_t
#define TYPE_TB0CTL_L uint8_t
#define TYPE_TB0EX0 uint16_t
#define TYPE_TB0EX0_H uint8_t
#define TYPE_TB0EX0_L uint8_t
#define TYPE_TB0IV uint16_t
#define TYPE_TB0IV_H uint8_t
#define TYPE_TB0IV_L uint8_t
#define TYPE_TB0R uint16_t
#define TYPE_TB0R_H uint8_t
#define TYPE_TB0R_L uint8_t
#define TYPE_TBCCR0 uint16_t
#define TYPE_TBCCR1 uint16_t
#define TYPE_TBCCR2 uint16_t
#define TYPE_TBCCR3 uint16_t
#define TYPE_TBCCR4 uint16_t
#define TYPE_TBCCR5 uint16_t
#define TYPE_TBCCR6 uint16_t
#define TYPE_TBCCTL0 uint16_t
#define TYPE_TBCCTL1 uint16_t
#define TYPE_TBCCTL2 uint16_t
#define TYPE_TBCCTL3 uint16_t
#define TYPE_TBCCTL4 uint16_t
#define TYPE_TBCCTL5 uint16_t
#define TYPE_TBCCTL6 uint16_t
#define TYPE_TBCTL uint16_t
#define TYPE_TBIV uint16_t
#define TYPE_TBR uint16_t
#define TYPE_TCCTL uint8_t
#define TYPE_TCDAT uint8_t
#define TYPE_TCPLD uint8_t
#define TYPE_TD0CCR0 uint16_t
#define TYPE_TD0CCR0_H uint8_t
#define TYPE_TD0CCR0_L uint8_t
#define TYPE_TD0CCR1 uint16_t
#define TYPE_TD0CCR1_H uint8_t
#define TYPE_TD0CCR1_L uint8_t
#define TYPE_TD0CCR2 uint16_t
#define TYPE_TD0CCR2_H uint8_t
#define TYPE_TD0CCR2_L uint8_t
#define TYPE_TD0CCTL0 uint16_t
#define TYPE_TD0CCTL0_H uint8_t
#define TYPE_TD0CCTL0_L uint8_t
#define TYPE_TD0CCTL1 uint16_t
#define TYPE_TD0CCTL1_H uint8_t
#define TYPE_TD0CCTL1_L uint8_t
#define TYPE_TD0CCTL2 uint16_t
#define TYPE_TD0CCTL2_H uint8_t
#define TYPE_TD0CCTL2_L uint8_t
#define TYPE_TD0CL0 uint16_t
#define TYPE_TD0CL0_H uint8_t
#define TYPE_TD0CL0_L uint8_t
#define TYPE_TD0CL1 uint16_t
#define TYPE_TD0CL1_H uint8_t
#define TYPE_TD0CL1_L uint8_t
#define TYPE_TD0CL2 uint16_t
#define TYPE_TD0CL2_H uint8_t
#define TYPE_TD0CL2_L uint8_t
#define TYPE_TD0CTL0 uint16_t
#define TYPE_TD0CTL0_H uint8_t
#define TYPE_TD0CTL0_L uint8_t
#define TYPE_TD0CTL1 uint16_t
#define TYPE_TD0CTL1_H uint8_t
#define TYPE_TD0CTL1_L uint8_t
#define TYPE_TD0CTL2 uint16_t
#define TYPE_TD0CTL2_H uint8_t
#define TYPE_TD0CTL2_L uint8_t
#define TYPE_TD0HCTL0 uint16_t
#define TYPE_TD0HCTL0_H uint8_t
#define TYPE_TD0HCTL0_L uint8_t
#define TYPE_TD0HCTL1 uint16_t
#define TYPE_TD0HCTL1_H uint8_t
#define TYPE_TD0HCTL1_L uint8_t
#define TYPE_TD0HINT uint16_t
#define TYPE_TD0HINT_H uint8_t
#define TYPE_TD0HINT_L uint8_t
#define TYPE_TD0IV uint16_t
#define TYPE_TD0IV_H uint8_t
#define TYPE_TD0IV_L uint8_t
#define TYPE_TD0R uint16_t
#define TYPE_TD0R_H uint8_t
#define TYPE_TD0R_L uint8_t
#define TYPE_TD1CCR0 uint16_t
#define TYPE_TD1CCR0_H uint8_t
#define TYPE_TD1CCR0_L uint8_t
#define TYPE_TD1CCR1 uint16_t
#define TYPE_TD1CCR1_H uint8_t
#define TYPE_TD1CCR1_L uint8_t
#define TYPE_TD1CCR2 uint16_t
#define TYPE_TD1CCR2_H uint8_t
#define TYPE_TD1CCR2_L uint8_t
#define TYPE_TD1CCTL0 uint16_t
#define TYPE_TD1CCTL0_H uint8_t
#define TYPE_TD1CCTL0_L uint8_t
#define TYPE_TD1CCTL1 uint16_t
#define TYPE_TD1CCTL1_H uint8_t
#define TYPE_TD1CCTL1_L uint8_t
#define TYPE_TD1CCTL2 uint16_t
#define TYPE_TD1CCTL2_H uint8_t
#define TYPE_TD1CCTL2_L uint8_t
#define TYPE_TD1CL0 uint16_t
#define TYPE_TD1CL0_H uint8_t
#define TYPE_TD1CL0_L uint8_t
#define TYPE_TD1CL1 uint16_t
#define TYPE_TD1CL1_H uint8_t
#define TYPE_TD1CL1_L uint8_t
#define TYPE_TD1CL2 uint16_t
#define TYPE_TD1CL2_H uint8_t
#define TYPE_TD1CL2_L uint8_t
#define TYPE_TD1CTL0 uint16_t
#define TYPE_TD1CTL0_H uint8_t
#define TYPE_TD1CTL0_L uint8_t
#define TYPE_TD1CTL1 uint16_t
#define TYPE_TD1CTL1_H uint8_t
#define TYPE_TD1CTL1_L uint8_t
#define TYPE_TD1CTL2 uint16_t
#define TYPE_TD1CTL2_H uint8_t
#define TYPE_TD1CTL2_L uint8_t
#define TYPE_TD1HCTL0 uint16_t
#define TYPE_TD1HCTL0_H uint8_t
#define TYPE_TD1HCTL0_L uint8_t
#define TYPE_TD1HCTL1 uint16_t
#define TYPE_TD1HCTL1_H uint8_t
#define TYPE_TD1HCTL1_L uint8_t
#define TYPE_TD1HINT uint16_t
#define TYPE_TD1HINT_H uint8_t
#define TYPE_TD1HINT_L uint8_t
#define TYPE_TD1IV uint16_t
#define TYPE_TD1IV_H uint8_t
#define TYPE_TD1IV_L uint8_t
#define TYPE_TD1R uint16_t
#define TYPE_TD1R_H uint8_t
#define TYPE_TD1R_L uint8_t
#define TYPE_TEC0IV uint16_t
#define TYPE_TEC0IV_H uint8_t
#define TYPE_TEC0IV_L uint8_t
#define TYPE_TEC0STA uint16_t
#define TYPE_TEC0STA_H uint8_t
#define TYPE_TEC0STA_L uint8_t
#define TYPE_TEC0XCTL0 uint16_t
#define TYPE_TEC0XCTL0_H uint8_t
#define TYPE_TEC0XCTL0_L uint8_t
#define TYPE_TEC0XCTL1 uint16_t
#define TYPE_TEC0XCTL1_H uint8_t
#define TYPE_TEC0XCTL1_L uint8_t
#define TYPE_TEC0XCTL2 uint16_t
#define TYPE_TEC0XCTL2_H uint8_t
#define TYPE_TEC0XCTL2_L uint8_t
#define TYPE_TEC0XINT uint16_t
#define TYPE_TEC0XINT_H uint8_t
#define TYPE_TEC0XINT_L uint8_t
#define TYPE_TEC1IV uint16_t
#define TYPE_TEC1IV_H uint8_t
#define TYPE_TEC1IV_L uint8_t
#define TYPE_TEC1STA uint16_t
#define TYPE_TEC1STA_H uint8_t
#define TYPE_TEC1STA_L uint8_t
#define TYPE_TEC1XCTL0 uint16_t
#define TYPE_TEC1XCTL0_H uint8_t
#define TYPE_TEC1XCTL0_L uint8_t
#define TYPE_TEC1XCTL1 uint16_t
#define TYPE_TEC1XCTL1_H uint8_t
#define TYPE_TEC1XCTL1_L uint8_t
#define TYPE_TEC1XCTL2 uint16_t
#define TYPE_TEC1XCTL2_H uint8_t
#define TYPE_TEC1XCTL2_L uint8_t
#define TYPE_TEC1XINT uint16_t
#define TYPE_TEC1XINT_H uint8_t
#define TYPE_TEC1XINT_L uint8_t
#define TYPE_TLV_ADC12_1_LEN uint8_t
#define TYPE_TLV_ADC12_1_TAG uint8_t
#define TYPE_TLV_CHECKSUM uint16_t
#define TYPE_TLV_DCO_30_LEN uint8_t
#define TYPE_TLV_DCO_30_TAG uint8_t
#define TYPE_TPCNT1 uint8_t
#define TYPE_TPCNT2 uint8_t
#define TYPE_TPCTL uint8_t
#define TYPE_TPD uint8_t
#define TYPE_TPE uint8_t
#define TYPE_TXBUF uint8_t
#define TYPE_TXBUF0 uint8_t
#define TYPE_TXBUF1 uint8_t
#define TYPE_TXBUF_0 uint8_t
#define TYPE_TXBUF_1 uint8_t
#define TYPE_U0BR0 uint8_t
#define TYPE_U0BR1 uint8_t
#define TYPE_U0CTL uint8_t
#define TYPE_U0MCTL uint8_t
#define TYPE_U0RCTL uint8_t
#define TYPE_U0RXBUF uint8_t
#define TYPE_U0TCTL uint8_t
#define TYPE_U0TXBUF uint8_t
#define TYPE_U1BR0 uint8_t
#define TYPE_U1BR1 uint8_t
#define TYPE_U1CTL uint8_t
#define TYPE_U1MCTL uint8_t
#define TYPE_U1RCTL uint8_t
#define TYPE_U1RXBUF uint8_t
#define TYPE_U1TCTL uint8_t
#define TYPE_U1TXBUF uint8_t
#define TYPE_UBR0 uint8_t
#define TYPE_UBR00 uint8_t
#define TYPE_UBR01 uint8_t
#define TYPE_UBR0_0 uint8_t
#define TYPE_UBR0_1 uint8_t
#define TYPE_UBR1 uint8_t
#define TYPE_UBR10 uint8_t
#define TYPE_UBR11 uint8_t
#define TYPE_UBR1_0 uint8_t
#define TYPE_UBR1_1 uint8_t
#define TYPE_UC0IE uint8_t
#define TYPE_UC0IFG uint8_t
#define TYPE_UC1IE uint8_t
#define TYPE_UC1IFG uint8_t
#define TYPE_UCA0ABCTL uint8_t
#define TYPE_UCA0BR0 uint8_t
#define TYPE_UCA0BR1 uint8_t
#define TYPE_UCA0BRW uint16_t
#define TYPE_UCA0BRW_H uint8_t
#define TYPE_UCA0BRW_L uint8_t
#define TYPE_UCA0CTL0 uint8_t
#define TYPE_UCA0CTL1 uint8_t
#define TYPE_UCA0CTLW0 uint16_t
#define TYPE_UCA0CTLW0_H uint8_t
#define TYPE_UCA0CTLW0_L uint8_t
#define TYPE_UCA0ICTL uint16_t
#define TYPE_UCA0ICTL_H uint8_t
#define TYPE_UCA0ICTL_L uint8_t
#define TYPE_UCA0IRCTL uint16_t
#define TYPE_UCA0IRCTL_H uint8_t
#define TYPE_UCA0IRCTL_L uint8_t
#define TYPE_UCA0IRRCTL uint8_t
#define TYPE_UCA0IRTCTL uint8_t
#define TYPE_UCA0IV uint16_t
#define TYPE_UCA0MCTL uint8_t
#define TYPE_UCA0RXBUF uint8_t
#define TYPE_UCA0STAT uint8_t
#define TYPE_UCA0TXBUF uint8_t
#define TYPE_UCA1ABCTL uint8_t
#define TYPE_UCA1BR0 uint8_t
#define TYPE_UCA1BR1 uint8_t
#define TYPE_UCA1BRW uint16_t
#define TYPE_UCA1BRW_H uint8_t
#define TYPE_UCA1BRW_L uint8_t
#define TYPE_UCA1CTL0 uint8_t
#define TYPE_UCA1CTL1 uint8_t
#define TYPE_UCA1CTLW0 uint16_t
#define TYPE_UCA1CTLW0_H uint8_t
#define TYPE_UCA1CTLW0_L uint8_t
#define TYPE_UCA1ICTL uint16_t
#define TYPE_UCA1ICTL_H uint8_t
#define TYPE_UCA1ICTL_L uint8_t
#define TYPE_UCA1IRCTL uint16_t
#define TYPE_UCA1IRCTL_H uint8_t
#define TYPE_UCA1IRCTL_L uint8_t
#define TYPE_UCA1IRRCTL uint8_t
#define TYPE_UCA1IRTCTL uint8_t
#define TYPE_UCA1IV uint16_t
#define TYPE_UCA1MCTL uint8_t
#define TYPE_UCA1RXBUF uint8_t
#define TYPE_UCA1STAT uint8_t
#define TYPE_UCA1TXBUF uint8_t
#define TYPE_UCA2ABCTL uint8_t
#define TYPE_UCA2BRW uint16_t
#define TYPE_UCA2BRW_H uint8_t
#define TYPE_UCA2BRW_L uint8_t
#define TYPE_UCA2CTLW0 uint16_t
#define TYPE_UCA2CTLW0_H uint8_t
#define TYPE_UCA2CTLW0_L uint8_t
#define TYPE_UCA2ICTL uint16_t
#define TYPE_UCA2ICTL_H uint8_t
#define TYPE_UCA2ICTL_L uint8_t
#define TYPE_UCA2IRCTL uint16_t
#define TYPE_UCA2IRCTL_H uint8_t
#define TYPE_UCA2IRCTL_L uint8_t
#define TYPE_UCA2IV uint16_t
#define TYPE_UCA2MCTL uint8_t
#define TYPE_UCA2STAT uint8_t
#define TYPE_UCA2TXBUF uint8_t
#define TYPE_UCA3ABCTL uint8_t
#define TYPE_UCA3BRW uint16_t
#define TYPE_UCA3BRW_H uint8_t
#define TYPE_UCA3BRW_L uint8_t
#define TYPE_UCA3CTLW0 uint16_t
#define TYPE_UCA3CTLW0_H uint8_t
#define TYPE_UCA3CTLW0_L uint8_t
#define TYPE_UCA3ICTL uint16_t
#define TYPE_UCA3ICTL_H uint8_t
#define TYPE_UCA3ICTL_L uint8_t
#define TYPE_UCA3IRCTL uint16_t
#define TYPE_UCA3IRCTL_H uint8_t
#define TYPE_UCA3IRCTL_L uint8_t
#define TYPE_UCA3IV uint16_t
#define TYPE_UCA3MCTL uint8_t
#define TYPE_UCA3STAT uint8_t
#define TYPE_UCA3TXBUF uint8_t
#define TYPE_UCB0BR0 uint8_t
#define TYPE_UCB0BR1 uint8_t
#define TYPE_UCB0BRW uint16_t
#define TYPE_UCB0BRW_H uint8_t
#define TYPE_UCB0BRW_L uint8_t
#define TYPE_UCB0CTL0 uint8_t
#define TYPE_UCB0CTL1 uint8_t
#define TYPE_UCB0CTLW0 uint16_t
#define TYPE_UCB0CTLW0_H uint8_t
#define TYPE_UCB0CTLW0_L uint8_t
#define TYPE_UCB0I2CIE uint8_t
#define TYPE_UCB0I2COA uint16_t
#define TYPE_UCB0I2COA_H uint8_t
#define TYPE_UCB0I2COA_L uint8_t
#define TYPE_UCB0I2CSA uint16_t
#define TYPE_UCB0I2CSA_H uint8_t
#define TYPE_UCB0I2CSA_L uint8_t
#define TYPE_UCB0ICTL uint16_t
#define TYPE_UCB0ICTL_H uint8_t
#define TYPE_UCB0ICTL_L uint8_t
#define TYPE_UCB0IV uint16_t
#define TYPE_UCB0RXBUF uint8_t
#define TYPE_UCB0STAT uint8_t
#define TYPE_UCB0TXBUF uint8_t
#define TYPE_UCB1BR0 uint8_t
#define TYPE_UCB1BR1 uint8_t
#define TYPE_UCB1BRW uint16_t
#define TYPE_UCB1BRW_H uint8_t
#define TYPE_UCB1BRW_L uint8_t
#define TYPE_UCB1CTL0 uint8_t
#define TYPE_UCB1CTL1 uint8_t
#define TYPE_UCB1CTLW0 uint16_t
#define TYPE_UCB1CTLW0_H uint8_t
#define TYPE_UCB1CTLW0_L uint8_t
#define TYPE_UCB1I2CIE uint8_t
#define TYPE_UCB1I2COA uint16_t
#define TYPE_UCB1I2COA_H uint8_t
#define TYPE_UCB1I2COA_L uint8_t
#define TYPE_UCB1I2CSA uint16_t
#define TYPE_UCB1I2CSA_H uint8_t
#define TYPE_UCB1I2CSA_L uint8_t
#define TYPE_UCB1ICTL uint16_t
#define TYPE_UCB1ICTL_H uint8_t
#define TYPE_UCB1ICTL_L uint8_t
#define TYPE_UCB1IV uint16_t
#define TYPE_UCB1RXBUF uint8_t
#define TYPE_UCB1STAT uint8_t
#define TYPE_UCB1TXBUF uint8_t
#define TYPE_UCB2BRW uint16_t
#define TYPE_UCB2BRW_H uint8_t
#define TYPE_UCB2BRW_L uint8_t
#define TYPE_UCB2CTLW0 uint16_t
#define TYPE_UCB2CTLW0_H uint8_t
#define TYPE_UCB2CTLW0_L uint8_t
#define TYPE_UCB2I2COA uint16_t
#define TYPE_UCB2I2COA_H uint8_t
#define TYPE_UCB2I2COA_L uint8_t
#define TYPE_UCB2I2CSA uint16_t
#define TYPE_UCB2I2CSA_H uint8_t
#define TYPE_UCB2I2CSA_L uint8_t
#define TYPE_UCB2ICTL uint16_t
#define TYPE_UCB2ICTL_H uint8_t
#define TYPE_UCB2ICTL_L uint8_t
#define TYPE_UCB2IV uint16_t
#define TYPE_UCB2STAT uint8_t
#define TYPE_UCB2TXBUF uint8_t
#define TYPE_UCB3BRW uint16_t
#define TYPE_UCB3BRW_H uint8_t
#define TYPE_UCB3BRW_L uint8_t
#define TYPE_UCB3CTLW0 uint16_t
#define TYPE_UCB3CTLW0_H uint8_t
#define TYPE_UCB3CTLW0_L uint8_t
#define TYPE_UCB3I2COA uint16_t
#define TYPE_UCB3I2COA_H uint8_t
#define TYPE_UCB3I2COA_L uint8_t
#define TYPE_UCB3I2CSA uint16_t
#define TYPE_UCB3I2CSA_H uint8_t
#define TYPE_UCB3I2CSA_L uint8_t
#define TYPE_UCB3ICTL uint16_t
#define TYPE_UCB3ICTL_H uint8_t
#define TYPE_UCB3ICTL_L uint8_t
#define TYPE_UCB3IV uint16_t
#define TYPE_UCB3STAT uint8_t
#define TYPE_UCB3TXBUF uint8_t
#define TYPE_UCSCTL0 uint16_t
#define TYPE_UCSCTL0_H uint8_t
#define TYPE_UCSCTL0_L uint8_t
#define TYPE_UCSCTL1 uint16_t
#define TYPE_UCSCTL1_H uint8_t
#define TYPE_UCSCTL1_L uint8_t
#define TYPE_UCSCTL2 uint16_t
#define TYPE_UCSCTL2_H uint8_t
#define TYPE_UCSCTL2_L uint8_t
#define TYPE_UCSCTL3 uint16_t
#define TYPE_UCSCTL3_H uint8_t
#define TYPE_UCSCTL3_L uint8_t
#define TYPE_UCSCTL4 uint16_t
#define TYPE_UCSCTL4_H uint8_t
#define TYPE_UCSCTL4_L uint8_t
#define TYPE_UCSCTL5 uint16_t
#define TYPE_UCSCTL5_H uint8_t
#define TYPE_UCSCTL5_L uint8_t
#define TYPE_UCSCTL6 uint16_t
#define TYPE_UCSCTL6_H uint8_t
#define TYPE_UCSCTL6_L uint8_t
#define TYPE_UCSCTL7 uint16_t
#define TYPE_UCSCTL7_H uint8_t
#define TYPE_UCSCTL7_L uint8_t
#define TYPE_UCSCTL8 uint16_t
#define TYPE_UCSCTL8_H uint8_t
#define TYPE_UCSCTL8_L uint8_t
#define TYPE_UCTL uint8_t
#define TYPE_UCTL0 uint8_t
#define TYPE_UCTL1 uint8_t
#define TYPE_UCTL_0 uint8_t
#define TYPE_UCTL_1 uint8_t
#define TYPE_UMCTL uint8_t
#define TYPE_UMCTL0 uint8_t
#define TYPE_UMCTL1 uint8_t
#define TYPE_UMCTL_0 uint8_t
#define TYPE_UMCTL_1 uint8_t
#define TYPE_URCTL uint8_t
#define TYPE_URCTL0 uint8_t
#define TYPE_URCTL1 uint8_t
#define TYPE_URCTL_0 uint8_t
#define TYPE_URCTL_1 uint8_t
#define TYPE_USBCNF uint16_t
#define TYPE_USBCNF_H uint8_t
#define TYPE_USBCNF_L uint8_t
#define TYPE_USBCTL uint8_t
#define TYPE_USBFN uint16_t
#define TYPE_USBFN_H uint8_t
#define TYPE_USBFN_L uint8_t
#define TYPE_USBFUNADR uint8_t
#define TYPE_USBIE uint8_t
#define TYPE_USBIEP0BUF uint8_t
#define TYPE_USBIEPBBAX_1 uint8_t
#define TYPE_USBIEPBBAX_2 uint8_t
#define TYPE_USBIEPBBAX_3 uint8_t
#define TYPE_USBIEPBBAX_4 uint8_t
#define TYPE_USBIEPBBAX_5 uint8_t
#define TYPE_USBIEPBBAX_6 uint8_t
#define TYPE_USBIEPBBAX_7 uint8_t
#define TYPE_USBIEPBBAY_1 uint8_t
#define TYPE_USBIEPBBAY_2 uint8_t
#define TYPE_USBIEPBBAY_3 uint8_t
#define TYPE_USBIEPBBAY_4 uint8_t
#define TYPE_USBIEPBBAY_5 uint8_t
#define TYPE_USBIEPBBAY_6 uint8_t
#define TYPE_USBIEPBBAY_7 uint8_t
#define TYPE_USBIEPBCTX_1 uint8_t
#define TYPE_USBIEPBCTX_2 uint8_t
#define TYPE_USBIEPBCTX_3 uint8_t
#define TYPE_USBIEPBCTX_4 uint8_t
#define TYPE_USBIEPBCTX_5 uint8_t
#define TYPE_USBIEPBCTX_6 uint8_t
#define TYPE_USBIEPBCTX_7 uint8_t
#define TYPE_USBIEPBCTY_1 uint8_t
#define TYPE_USBIEPBCTY_2 uint8_t
#define TYPE_USBIEPBCTY_3 uint8_t
#define TYPE_USBIEPBCTY_4 uint8_t
#define TYPE_USBIEPBCTY_5 uint8_t
#define TYPE_USBIEPBCTY_6 uint8_t
#define TYPE_USBIEPBCTY_7 uint8_t
#define TYPE_USBIEPCNF_0 uint8_t
#define TYPE_USBIEPCNF_1 uint8_t
#define TYPE_USBIEPCNF_2 uint8_t
#define TYPE_USBIEPCNF_3 uint8_t
#define TYPE_USBIEPCNF_4 uint8_t
#define TYPE_USBIEPCNF_5 uint8_t
#define TYPE_USBIEPCNF_6 uint8_t
#define TYPE_USBIEPCNF_7 uint8_t
#define TYPE_USBIEPCNT_0 uint8_t
#define TYPE_USBIEPIE uint8_t
#define TYPE_USBIEPIFG uint8_t
#define TYPE_USBIEPSIZXY_1 uint8_t
#define TYPE_USBIEPSIZXY_2 uint8_t
#define TYPE_USBIEPSIZXY_3 uint8_t
#define TYPE_USBIEPSIZXY_4 uint8_t
#define TYPE_USBIEPSIZXY_5 uint8_t
#define TYPE_USBIEPSIZXY_6 uint8_t
#define TYPE_USBIEPSIZXY_7 uint8_t
#define TYPE_USBIFG uint8_t
#define TYPE_USBKEYID uint16_t
#define TYPE_USBKEYID_H uint8_t
#define TYPE_USBKEYID_L uint8_t
#define TYPE_USBMAINT uint16_t
#define TYPE_USBMAINT_H uint8_t
#define TYPE_USBMAINT_L uint8_t
#define TYPE_USBOEP0BUF uint8_t
#define TYPE_USBOEPBBAX_1 uint8_t
#define TYPE_USBOEPBBAX_2 uint8_t
#define TYPE_USBOEPBBAX_3 uint8_t
#define TYPE_USBOEPBBAX_4 uint8_t
#define TYPE_USBOEPBBAX_5 uint8_t
#define TYPE_USBOEPBBAX_6 uint8_t
#define TYPE_USBOEPBBAX_7 uint8_t
#define TYPE_USBOEPBBAY_1 uint8_t
#define TYPE_USBOEPBBAY_2 uint8_t
#define TYPE_USBOEPBBAY_3 uint8_t
#define TYPE_USBOEPBBAY_4 uint8_t
#define TYPE_USBOEPBBAY_5 uint8_t
#define TYPE_USBOEPBBAY_6 uint8_t
#define TYPE_USBOEPBBAY_7 uint8_t
#define TYPE_USBOEPBCTX_1 uint8_t
#define TYPE_USBOEPBCTX_2 uint8_t
#define TYPE_USBOEPBCTX_3 uint8_t
#define TYPE_USBOEPBCTX_4 uint8_t
#define TYPE_USBOEPBCTX_5 uint8_t
#define TYPE_USBOEPBCTX_6 uint8_t
#define TYPE_USBOEPBCTX_7 uint8_t
#define TYPE_USBOEPBCTY_1 uint8_t
#define TYPE_USBOEPBCTY_2 uint8_t
#define TYPE_USBOEPBCTY_3 uint8_t
#define TYPE_USBOEPBCTY_4 uint8_t
#define TYPE_USBOEPBCTY_5 uint8_t
#define TYPE_USBOEPBCTY_6 uint8_t
#define TYPE_USBOEPBCTY_7 uint8_t
#define TYPE_USBOEPCNF_0 uint8_t
#define TYPE_USBOEPCNF_1 uint8_t
#define TYPE_USBOEPCNF_2 uint8_t
#define TYPE_USBOEPCNF_3 uint8_t
#define TYPE_USBOEPCNF_4 uint8_t
#define TYPE_USBOEPCNF_5 uint8_t
#define TYPE_USBOEPCNF_6 uint8_t
#define TYPE_USBOEPCNF_7 uint8_t
#define TYPE_USBOEPCNT_0 uint8_t
#define TYPE_USBOEPIE uint8_t
#define TYPE_USBOEPIFG uint8_t
#define TYPE_USBOEPSIZXY_1 uint8_t
#define TYPE_USBOEPSIZXY_2 uint8_t
#define TYPE_USBOEPSIZXY_3 uint8_t
#define TYPE_USBOEPSIZXY_4 uint8_t
#define TYPE_USBOEPSIZXY_5 uint8_t
#define TYPE_USBOEPSIZXY_6 uint8_t
#define TYPE_USBOEPSIZXY_7 uint8_t
#define TYPE_USBPHYCTL uint16_t
#define TYPE_USBPHYCTL_H uint8_t
#define TYPE_USBPHYCTL_L uint8_t
#define TYPE_USBPLLCTL uint16_t
#define TYPE_USBPLLCTL_H uint8_t
#define TYPE_USBPLLCTL_L uint8_t
#define TYPE_USBPLLDIVB uint16_t
#define TYPE_USBPLLDIVB_H uint8_t
#define TYPE_USBPLLDIVB_L uint8_t
#define TYPE_USBPLLIR uint16_t
#define TYPE_USBPLLIR_H uint8_t
#define TYPE_USBPLLIR_L uint8_t
#define TYPE_USBPWRCTL uint16_t
#define TYPE_USBPWRCTL_H uint8_t
#define TYPE_USBPWRCTL_L uint8_t
#define TYPE_USBSTABUFF uint8_t
#define TYPE_USBSUBLK uint8_t
#define TYPE_USBTOPBUFF uint8_t
#define TYPE_USBTSREG uint16_t
#define TYPE_USBTSREG_H uint8_t
#define TYPE_USBTSREG_L uint8_t
#define TYPE_USBVECINT uint16_t
#define TYPE_USBVECINT_H uint8_t
#define TYPE_USBVECINT_L uint8_t
#define TYPE_USICCTL uint16_t
#define TYPE_USICKCTL uint8_t
#define TYPE_USICNT uint8_t
#define TYPE_USICTL uint16_t
#define TYPE_USICTL0 uint8_t
#define TYPE_USICTL1 uint8_t
#define TYPE_USISR uint16_t
#define TYPE_USISRH uint8_t
#define TYPE_USISRL uint8_t
#define TYPE_UTCTL uint8_t
#define TYPE_UTCTL0 uint8_t
#define TYPE_UTCTL1 uint8_t
#define TYPE_UTCTL_0 uint8_t
#define TYPE_UTCTL_1 uint8_t
#define TYPE_WDTCTL uint16_t
#define TYPE_WDTCTL_H uint8_t
#define TYPE_WDTCTL_L uint8_t

#endif//_H_msp430regtypes_h

