# -*- mode: makefile-gmake; mode: flyspell-prog; -*-

COMPONENT=ClockAppC
PFLAGS+=-I$(TINYOS_ROOT_DIR)/chips/max6951
PFLAGS+=-I$(TINYOS_ROOT_DIR)/chips/max549
include $(TINYOS_ROOT_DIR)/Makefile.include

# vim: set noet ts=8 sw=8:
